//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContanctListApp_v2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
        public int id { get; set; }
        [DisplayName("Name")]
        public string name { get; set; }
        [DisplayName("Surname")]
        public string surname { get; set; }
        [DisplayName("E-Mail")]
        [Required]
        public string email { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        public string password { get; set; }
       
        [DisplayName("Category")]
        public Nullable<int> categoryId { get; set; }
        [DisplayName("Another category")]
        public string anotherCategory { get; set; }
        [DisplayName("Phone")]
        public string phone { get; set; }
        [DisplayName("Date of birth")]
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        [DisplayName("Business category")]
        public Nullable<int> BuisnessCategoryId { get; set; }
    
        public virtual BuisnessCategory BuisnessCategory { get; set; }
        public virtual Category Category { get; set; }
    }
}
